[build]
  command = """
  apt-get update &&
  apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev &&
  pip install --upgrade pip &&
  pip install -r requirements.txt &&
  python manage.py collectstatic --noinput &&
  python manage.py migrate &&
  gunicorn stage0.wsgi
  """
  publish = "staticfiles"

[build.environment]
  DJANGO_SETTINGS_MODULE = "stage0.settings"
  PYTHONUNBUFFERED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200